version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    build:
      context: ./
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
